### ISSUE TITLE
test CRDTs with (de)serialisation factored in

### ISSUE THREAD

**Issue by pgte** [ipfs-shipyard/js-delta-crdts#13]
Mentioned by @dirkmc, [this problem](https://github.com/ipfs-shipyard/js-delta-crdts/pull/11) was triggered by msgpack encode / decode properties.

There should be a way of performing the tests with differences introduced by serialisation / deserialization factored in.

**Comment by dirkmc** [comment]
I suggest

1. Add a module to js-delta-crdts that exports
  - `getReplica(type, id)`
    - `type`: Type of CRDT (eg 'RGA')
    - `id`: eg 'my rga'
    Defaults to `CRDT(type)(id)`
  - `implementReplica(fn)`
    - `fn`: a function that implements `getReplica()`

2. modify the tests to use `getReplica()` and await a synchronization function before checking `replace.value()`

3. Add a script to peer-star-app that
  - calls `implementReplica()` with a function that returns a `Shared`
  - Programmatically executes the js-delta-crdts tests ([this is easy with mocha](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically))

**Comment by dirkmc** [comment]
Ah great this PR looks like it takes care of the issue in a simpler way, I think we can close this issue right?

**Comment by pgte** [comment]
I went with a different approach on this. Instead of entering the tests in peer-star-app, I made a custom serialization package (delta-crdts-msgpack-codec) and use it to test the transmission on deltas.
(Also managed to catch a few bugs on a new feature with this).

This landed on v0.4.0.
