### ISSUE TITLE
Investigating issue with RGA inconsistency in peer-pad

### ISSUE THREAD

**Issue by jimpick** [ipfs-shipyard/js-delta-crdts#32]
I'm actively investigating an issue in peer-pad that might be a CRDT issue:

https://github.com/ipfs-shipyard/peer-pad/issues/267

**Comment by pgte** [comment]
@jimpick watch out that what you probably want to investigate is the source of the inconsistency: what was the state before a "bad" join happened.
If you have just the result of a bad join, joining it with the "right" state is not supposed to "fix it".

**Comment by pgte** [comment]
@jimpick would you say this was fixed by #33 and #35?

**Comment by jimpick** [comment]
Yes, this particular issue was fixed. There are still some problems, but I'll open a new issue for that.
