### ISSUE TITLE
Add updateAt to RGA

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/js-delta-crdts#6]
Would it be possible to add `updateAt(pos, value)` mutation to the RGA?

I'm using `removeAt(pos)` + `insertAt(pos, value)` to update values but it isn't an atomic operation and it causes a item to be removed momentarily. The use case is for the [todo-dapp](https://github.com/ipfs-shipyard/workshop-todo-app) I'm building but it's common enough to consider adding for other use-cases as well.

**Comment by pgte** [comment]
Landed in v0.2.5
