### ISSUE TITLE
Creating maps

### ISSUE THREAD

**Issue by salzhrani** [ipfs-shipyard/js-delta-crdts#9]
How would someone implement a map?
The paper explains that all embedded data types should 
> have a common causal context to the whole map

I believe JSON CRDT has the same constraint for maps

sharing the CC can be done by adding an additional argument to current type factories to use an existing `DotContext` instead of creating one.

also, should the keys of the map be stored as a CRDT Set? to handle concurrent adding and removing of keys?
What about the Map values? would a plain javascript object suffice to lookup the data type associated with that key?

I currently can't understand Operational Semantics so I can't comprehend figure 17 of the paper.

**Comment by pgte** [comment]
> sharing the CC can be done by adding an additional argument to current type factories to use an existing `DotContext` instead of creating one.

I agree, that would be required to keep causal consistency inside embeds. Embeds is not something we support out of the box (it can be emulated using causal delivery), but it would be good to have that.
The `DotContext` instance could optionally be passed into `type.initial()`. What do you think?

> also, should the keys of the map be stored as a CRDT Set? to handle concurrent adding and removing of keys?
> What about the Map values? would a plain javascript object suffice to lookup the data type associated with that key?

By reading the spec for the Observed-Remove Map, I don't think the keys need to be stored separately. I think that a Map would suffice, which, together with the clock, would make a delta.

<img width="687" alt="https___arxiv_org_pdf_1603_01529_pdf" src="https://user-images.githubusercontent.com/47910/44608029-46fd6e80-a7ea-11e8-96e2-ade18aed163a.png">

Here, `oδi` is the mutator of the embedded type, which returns the value and the new clock (`c'`).

@salzhrani would you like to take a shot at implementing this?

**Comment by pgte** [comment]
I'm going to have a go at this.
As a reference, I'm going to use this Elixir implementation: https://github.com/derekkraan/delta_crdt_ex/tree/master/lib/delta_crdt

**Comment by pgte** [comment]
This feature landed on v0.4.0.
You can check out [the ORMap documentation](https://github.com/ipfs-shipyard/js-delta-crdts#maps)

**Comment by salzhrani** [comment]
Amazing. Thanks
